import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createRewardsStyles = (colors: ColorScheme) => StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  content: { padding: 24, paddingBottom: 36 },
  header: { flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 22 },
  headerIcon: { width: 56, height: 56, borderRadius: 17, justifyContent: "center", alignItems: "center" },
  title: { color: colors.text, fontSize: 32, fontWeight: "800" },
  subtitle: { color: colors.textMuted, fontSize: 14, marginTop: 2 },
  balanceCard: { borderRadius: 20, padding: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 28 },
  balanceLabel: { color: "#166534", fontSize: 14, fontWeight: "700" },
  balanceValue: { color: "#14532d", fontSize: 27, fontWeight: "900", marginTop: 2 },
  deductionText: { position: "absolute", right: 18, top: 12, color: "#dc2626", fontSize: 18, fontWeight: "900" },
  sectionTitle: { color: colors.text, fontSize: 20, fontWeight: "800", marginBottom: 14 },
  rewardsHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  addRewardButton: { flexDirection: "row", alignItems: "center", gap: 3, borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 7, marginBottom: 14 },
  addRewardText: { fontSize: 13, fontWeight: "800" },
  rewardsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  rewardCard: { width: "47.5%", backgroundColor: colors.surface, borderRadius: 19, padding: 15, borderWidth: 1, borderColor: colors.border, minHeight: 190 },
  rewardIcon: { width: 46, height: 46, borderRadius: 14, justifyContent: "center", alignItems: "center", marginBottom: 13 },
  rewardName: { color: colors.text, fontSize: 16, fontWeight: "800", minHeight: 42 },
  rewardDescription: { color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: 5, flex: 1 },
  rewardFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 13 },
  cost: { color: colors.success, fontSize: 14, fontWeight: "800" },
  buyButton: { borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8 },
  buyText: { color: "#ffffff", fontWeight: "800", fontSize: 13 },
  history: { marginTop: 28 },
  historyCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 9, borderWidth: 1, borderColor: colors.border },
  historyName: { color: colors.text, fontWeight: "700", fontSize: 15 },
  historyCost: { color: colors.danger, fontWeight: "800" },
  emptyHistory: { color: colors.textMuted, fontSize: 14 },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15, 23, 42, 0.5)" },
  modalCard: { borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingBottom: 38 },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 22 },
  modalTitle: { fontSize: 22, fontWeight: "900" },
  modalSubtitle: { fontSize: 14, marginTop: 4 },
  inputLabel: { fontSize: 14, fontWeight: "800", marginBottom: 7, marginTop: 13 },
  input: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15 },
  descriptionInput: { minHeight: 74, textAlignVertical: "top" },
  workTimeHelper: { flexDirection: "row", alignItems: "flex-start", gap: 7, marginTop: 9, paddingHorizontal: 2 },
  workTimeText: { flex: 1, fontSize: 13, lineHeight: 18 },
  quickCostRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  quickCostBadge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  quickCostText: { fontSize: 12, fontWeight: "800" },
  saveButton: { borderRadius: 14, paddingVertical: 15, alignItems: "center", marginTop: 24 },
  saveButtonText: { color: "#fff", fontSize: 16, fontWeight: "800" },
});
